[2024-12-08T01:10:43.123+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_to_vertica.create_table scheduled__2024-12-07T00:00:00+00:00 [queued]>
[2024-12-08T01:10:43.126+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_to_vertica.create_table scheduled__2024-12-07T00:00:00+00:00 [queued]>
[2024-12-08T01:10:43.126+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2024-12-08T01:10:43.130+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_table> on 2024-12-07 00:00:00+00:00
[2024-12-08T01:10:43.133+0000] {standard_task_runner.py:57} INFO - Started process 1100 to run task
[2024-12-08T01:10:43.134+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_data_to_vertica', 'create_table', 'scheduled__2024-12-07T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/vertica_load_dag.py', '--cfg-path', '/tmp/tmpibdyo7xa']
[2024-12-08T01:10:43.136+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask create_table
[2024-12-08T01:10:43.154+0000] {task_command.py:415} INFO - Running <TaskInstance: load_data_to_vertica.create_table scheduled__2024-12-07T00:00:00+00:00 [running]> on host ca898f8eb629
[2024-12-08T01:10:43.188+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_to_vertica' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-07T00:00:00+00:00'
[2024-12-08T01:10:43.188+0000] {sql.py:274} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS grade.example_table (
            id INT PRIMARY KEY,
            data VARCHAR(255)
        );
        
[2024-12-08T01:10:43.192+0000] {base.py:73} INFO - Using connection ID 'vertica_conn' for task execution.
[2024-12-08T01:10:43.195+0000] {base.py:73} INFO - Using connection ID 'vertica_conn' for task execution.
[2024-12-08T01:10:43.197+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.164.63.200", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-12-08T01:10:43.201+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=load_data_to_vertica, task_id=create_table, execution_date=20241207T000000, start_date=20241208T011043, end_date=20241208T011043
[2024-12-08T01:10:43.205+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task create_table (connection to server at "10.164.63.200", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 1100)
[2024-12-08T01:10:43.234+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-08T01:10:43.243+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
