[2024-12-06T09:09:59.687+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_to_vertica.create_table manual__2024-12-06T09:03:42.688468+00:00 [queued]>
[2024-12-06T09:09:59.690+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_to_vertica.create_table manual__2024-12-06T09:03:42.688468+00:00 [queued]>
[2024-12-06T09:09:59.690+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 1
[2024-12-06T09:09:59.694+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_table> on 2024-12-06 09:03:42.688468+00:00
[2024-12-06T09:09:59.696+0000] {standard_task_runner.py:57} INFO - Started process 279 to run task
[2024-12-06T09:09:59.697+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_data_to_vertica', 'create_table', 'manual__2024-12-06T09:03:42.688468+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/vertica_load_dag.py', '--cfg-path', '/tmp/tmpkgojeec3']
[2024-12-06T09:09:59.698+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask create_table
[2024-12-06T09:09:59.718+0000] {task_command.py:415} INFO - Running <TaskInstance: load_data_to_vertica.create_table manual__2024-12-06T09:03:42.688468+00:00 [running]> on host c8f6c342c5cd
[2024-12-06T09:09:59.748+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_data_to_vertica' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T09:03:42.688468+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T09:03:42.688468+00:00'
[2024-12-06T09:09:59.749+0000] {sql.py:274} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS grade.example_table (
            id INT PRIMARY KEY,
            data VARCHAR(255)
        );
        
[2024-12-06T09:09:59.752+0000] {base.py:73} INFO - Using connection ID 'vertica_conn' for task execution.
[2024-12-06T09:09:59.756+0000] {base.py:73} INFO - Using connection ID 'vertica_conn' for task execution.
[2024-12-06T09:11:14.765+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "10.164.63.200", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2024-12-06T09:11:14.792+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=load_data_to_vertica, task_id=create_table, execution_date=20241206T090342, start_date=20241206T090959, end_date=20241206T091114
[2024-12-06T09:11:14.803+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 27 for task create_table (connection to server at "10.164.63.200", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 279)
[2024-12-06T09:11:14.845+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-06T09:11:14.864+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
